Prometheus to sqlite functionality
aau-p9s/autoscaler-frontend pull request #11
Opened 2024-11-22 12:45 UTC by Mast3rwaf1z

2024-11-22 17:53 UTC, Jaffenheimer requested changes
Det ser generelt nice ud, har et spørgsmål og en enkelt kommentar

2024-11-22 17:53 UTC, Jaffenheimer commented on autoscaler-frontend/autoscaler-frontend/Database/Database.cs
> +                id INTEGER PRIMARY KEY,
Er id bare en integer der auto incrementer? (Er vant til mysql hvor man skal skrive det explicit)

2024-11-22 17:53 UTC, Jaffenheimer commented on autoscaler-frontend/autoscaler-frontend/Database/PrometheusGenerator.cs
Måske noget error handling i den her fil kunne være nice, der er rimelig mange possible null reference warnings, og når det er HTTP kald kan det jo godt fejle hvis prometheus dør, hvor vi nok ikke er interresserede i at vores aplication også gør det

2024-11-22 18:51 UTC, Mast3rwaf1z commented on autoscaler-frontend/autoscaler-frontend/Database/Database.cs
> +                id INTEGER PRIMARY KEY,
Ja

2024-11-23 00:46 UTC, Mast3rwaf1z commented on autoscaler-frontend/autoscaler-frontend/Database/PrometheusGenerator.cs
done

2024-11-24 08:17 UTC, Jaffenheimer approved these changes
Nice 👍 lgtm

2024-11-25 08:46 UTC, merged